FROM camunda/camunda:8.9.0-alpha4

# Database configuration (RDBMS with H2)
# Use H2 as the internal database for easy setup (not for production)
ENV CAMUNDA_DATA_SECONDARY_STORAGE_TYPE=rdbms
ENV SPRING_DATASOURCE_URL=jdbc:h2:mem:camunda8;DB_CLOSE_DELAY=-1
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
ENV SPRING_DATASOURCE_USERNAME=sa
ENV SPRING_DATASOURCE_PASSWORD=

# Enable essential web components and security
ENV CAMUNDA_OPERATE_ENABLED=true
ENV CAMUNDA_OPTIMIZE_ENABLED=false
ENV CAMUNDA_TASKLIST_ENABLED=true
ENV CAMUNDA_ZEEBE_GATEWAY_SECURITY_ENABLED=true
ENV ZEEBE_STANDALONE_GATEWAY=true

# Set initial administrative credentials
ENV CAMUNDA_IDENTITY_INITIAL_USER_PASSWORD=demo
ENV CAMUNDA_IDENTITY_INITIAL_USER_NAME=demo

# Enable Basic Authentication for the REST API
ENV CAMUNDA_REST_INTERCEPTORS_AUTH_BASIC_ENABLED=true
ENV CAMUNDA_IDENTITY_INITIAL_USER_PASSWORD=demo
ENV CAMUNDA_IDENTITY_INITIAL_USER_NAME=demo
